#Problem 30: Finding a Spliced Motif
#Given: Two DNA strings s and t (each of length at most 1 kbp) in FASTA format.
#Return: One collection of indices of s in which the symbols of t appear as a subsequence of s. If multiple solutions exist, you may return any one.

string1 = 'CCTCCTTCGGCGGTCGGCCAATATCGTAGTATTTTTGGTTGACTCGCAGTACACCAAATCTAGGGCCACGAATTTGGGTGGACCGACAATGCTCAATGACCCGCGTCGGACATATATATTGTGTCGGTGGCTGACGGACGCTAGATCCCAGGTGTAAGCGTTGGACTCAGACGATTCCCTGTTACTCAGAGACGGCCGACGCAAAGCGGGGGTCGGGCATGCGTGGAAGGAGCTGCTTCATACTTAATATCGGCCTCTATCGTTTACGTTCTGCCCCATTACGGCAACACCAGGCCGCCAACGGTAGGGAATAGTTAGCATCCTGATGCCTAAATGACACTAACCAAGGCTTGCGCAGGAGTTTACTGGGGCTCTCCAGGCTATTCGCTCGGAATGGTAGGCCGCTTACTTGAACGTAATGATCCCTCGAGACGCGGCGCCTATATTCCGCCCCATCGATTCCATCGCGCCGGGAACCATATCCAGTCGTCCATGGCAGACTGTAGGGGCATGCACCAGTACTAATTGTGCTTAGAAGCGGTAACCCGCAACATCAGTAGCACGGACCATTTAATTCTACCTCACCTAGCCTATGCACGAGTTTCTATTAGCAACATGCACTGACGGACCGTTGGGTCACCTCGTGAGCTTTAAGCTGATTCACAGAACAGGGGGTGGTTTACGAGATTTCTCGAGCAGCGGGTAGCATAGACGCCGCTCCTCCACCCGTTTGCTGTTGTAGCAACAGCCATGTCATAAGCCTCGGTTAGGTGGGTTTTGGGGAATGCCTAGATGGAACGTGCCGTTGGCGTCGTAATCATACTTGGCTCGCAGTGCAGCAGGGGTCATTCGAGAGACGTCGTCATCGCAGTTATGGAGGACGCTCTACAGGTTACCCATTGAGCATCCATGTATCCAAGCTAGATGGTCGATTCATTACAGATAGGTAGTGCAAAGGGTAGCACTCCCGAGGTAAACGTCGTT'
string2 = 'GCAAATGACTCCACATCCTTTGGACCCGACAGATCAGGCACACTTACCAATGTGTGGTTTCATAGGTCTCCTGCCTTTAAGTAGTGAGTAACGAAGAC'

def findMotif(string1, string2):
    result = ''
    offset = 0
    for char in string2:
        found = string1.find(char)
        
        result = result + str(found + 1 + offset)  + " "
        
        offset = offset + found + 1
        string1 = string1[found + 1:]
    return result

print(findMotif(string1, string2))