using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


namespace ProjectRosalindcs
{
    class Program
    {
        static void Main(string[] args)
        {

            Console.WriteLine(RNA("CGGGCGGCCCCCCTCTACTGCAACGATCATAATGCCCCGTATTGGGCATAAAGACATTCTCTATGGCTGGCCACTATGGCATGCTTCGACATTTGGTATGAAAGAGGGACAGCGTTGACGCGTCTGGAACGGACCATGTATACACGGACTCTCGAGTAAGGTATCAAGAGGTGCGTCCTATAGCCGTTCCGCCTCACGATGGCTGCAGCCTAAATCGGGCATAACTACTAGGATACCGTGTCACCGCAATCTTAAACAATCCCCTGCCCTGCCCTGCTCGATGTATGCAGGTAGTGTTATTTGCCACGCCAAGCCCAAATCTGCTCCCCTTGAAATCTAATTAAAGAAATGCCGACCCATCGGCCAACGAGAACCAGGAAACTTGACCCCTTGGTACGCGCGGGGTTGTTGGATCCCTGTGCGCACCCTTGCCCGTGGAGGCATGCGCAAAGTTAATCTCATAGGGCTTCCTCTGGTTGCAAGATTCCAAATTTTTGTTAGTCGATATACGGACAGAGTCGTATGCTGGGAATCCCTGGCCGGAACGCCCTGAACCCCCCAATTTCTCCCCTCTACGATATTTAGAATGATCGCGAAGTTTTCTCATCAAGTAGGATGTTAGACATACAGGACAACAGTCACGAGACGCCTGGACGACTTCTTTGGACATGCACGGGTCCTGGGTTAACGGGAATCTGTCCCCTGTATCCAACGTTATGGGCGATGATCGAATCCGGCGTCTGAAGCTTGCAAAGAATATATATATTGATATAGGTATCCGAAAATGCTATCACCCTGTAAGCCATCTCCGGACATTAGCCATAGCGCGACGTCTTAACTAATCCACGGCTACCCTCTTTGACCCGCTCCGATATCTCCTTTTACTGATCTTCAGCTTCGGATAGAGGCAACCGGCTCAATCGTGCCGAGTCGGTGAACGATGAAATTACGGCCCTCGATTAGGATTTATGTAGATGCGAATTGGAGTGCAGTC"));
            Console.ReadLine();
        }

        static string RNA(string strDna)
        {
            return strDna.Replace("T", "U");
        }
    }
}
