/*
*/


static void Main(string[] args)
{
	Console.WriteLine(REVC("GGTTATTAATGCAGTGTTCGCATAATTACTGCAGCCTGAACTCCAGATGCATCGCTGGGCGTGCCCCAAAGAAAAAGACGGAGTCTGATCCTGTAGTATCGAGATCACGTATCTTCAAGACTTCGATTAATATGGTTTACTGTTTGACCGTTCACCTAAATAACATTTACGACCCACCCCTTCGATCTGAACCCGTATAGATGAAGTTCCCACCAACCGAGTTTCGGTAACCCTTCGTGTATATCTAGCGCGCCTGGTCGTCCCCTTAGCCAGAAACGCAAACACATTGGCCTGCATCTGCTCAAAAAACCTGTCTGGGGTATCCAACTACCTTCGCCGTATCTACCCTCCACTCGTACTGCTGATCTCTTACTCTGGGACTCCACCGATCTTAATGCTCATGACTTATTTGACGTTTCTCTATATGGCAAAAAAAAATAGTTTATCACTCACTCACGGTGAGGGTGCTCATTGCGAATGAAATCGTGTAGCGGTCGACCGCAGGTGTAGGGATACGTTATTGTCCTTAGGTTAACTGTTCGGACACATGACGGGATACCCGGACGAGGGCTCAACTCTTTAGTGATCAGTCCCTCACAGGCTTACATCATATCTGTATTGACGCTGAGAATCCGTTTTTAATGGCAGGCCCAATTTCGTTCCTGAGCCCGTGGAGCAGCGGTACAGGGAGCGGTAATCGGAAGAGCTTGCCAGCACCTTATGTTCACTGTTTTTGTAACTTTACTATCGCATGCTTTGCGTATTACCTATCTAGCTTTGGCGTCCTATAGGCTATGCCTCGCTGGCTGCCCTATCCGCCAGAGTATTAACGCAAACTTATTAGTCAGGATGCGCGTTAGAGAACTCATATGACGGCGACCAATTGGCAGTTAGCCGTCATCGCGGCTGCAACGATCTACTAC"));
	Console.ReadLine();
}

static string REVC(string strDna)
{
	char[] array = strDna.ToCharArray();
	Array.Reverse(array);
	return new String(array).Replace("T", "X").Replace("A", "T").Replace("X", "A").Replace("C", "X").Replace("G", "C").Replace("X", "G");
}
